Uncomment step after caching m2

diff --git a/.github/workflows/osl_publish_images_snapshots.yml b/.github/workflows/osl_publish_images_snapshots.yml
--- a/.github/workflows/osl_publish_images_snapshots.yml
+++ b/.github/workflows/osl_publish_images_snapshots.yml
@@ -64,68 +64,68 @@ jobs:
           DEPS_BRANCHNAME: ${{ inputs.IMAGE_TAG }}
           PNPM_FILTER: ${{ vars.IMAGES_UPSTREAM_PNPM_FILTER }}
 
-      # - name: "Build Images"
-      #   env:
-      #     DROOLS_AND_KOGITO__skip: true
-      #     KOGITO_RUNTIME_version: "${{ inputs.KOGITO_VERSION }}"
-      #     KIE_TOOLS_BUILD__buildContainerImages: "true"
-      #     KIE_TOOLS_BUILD__runEndToEndTests: "false"
-      #     KIE_TOOLS_BUILD__runTests:
-      #       "false"
-      #       # TODO: on upstream implement a root-env named defaultRegistry and defaultAccount and change on every image package
-      #     SONATAFLOW_BUILDER_IMAGE__registry: "quay.io"
-      #     SONATAFLOW_BUILDER_IMAGE__account: "kubesmarts"
-      #     SONATAFLOW_DEVMODE_IMAGE__registry: "quay.io"
-      #     SONATAFLOW_DEVMODE_IMAGE__account: "kubesmarts"
-      #     SONATAFLOW_MANAGEMENT_CONSOLE__registry: "quay.io"
-      #     SONATAFLOW_MANAGEMENT_CONSOLE__account: "kubesmarts"
-      #     KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__registry: "quay.io"
-      #     KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__account: "kubesmarts"
-      #     KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__registry: "quay.io"
-      #     KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__account: "kubesmarts"
-      #     KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__registry: "quay.io"
-      #     KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__account: "kubesmarts"
-      #     KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__registry: "quay.io"
-      #     KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__account: "kubesmarts"
-      #     SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageRegistry: "quay.io"
-      #     SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageAccount: "kubesmarts"
-      #     SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageRegistry: "quay.io"
-      #     SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageAccount: "kubesmarts"
-      #     SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageRegistry: "quay.io"
-      #     SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageAccount: "kubesmarts"
-      #     # SONATAFLOW_QUARKUS_DEVUI_VERSION: "${{ inputs.KOGITO_VERSION }}"
-      #     # SONATAFLOW_DEVMODE_IMAGE__sonataflowQuarkusDevUiVersion: "${{ inputs.KOGITO_VERSION }}"
-      #     DASHBUILDER__viewerImageRegistry: "quay.io"
-      #     DASHBUILDER__viewerImageAccount: "kubesmarts"
-      #     SONATAFLOW_OPERATOR__registry: "quay.io"
-      #     SONATAFLOW_OPERATOR__account: "kubesmarts"
-      #     KOGITO_DB_MIGRATOR_TOOL_IMAGE__registry: "quay.io"
-      #     KOGITO_DB_MIGRATOR_TOOL_IMAGE__account: "kubesmarts"
-      #   shell: bash
-      #   run: |
-      #     eval "pnpm ${{ vars.IMAGES_UPSTREAM_PNPM_FILTER }} --workspace-concurrency=1 build:prod"
-      #
-      # - name: "Login to Quay"
-      #   uses: docker/login-action@v3
-      #   with:
-      #     registry: quay.io
-      #     username: ${{ secrets.QUAY_ROBOT_ACCOUNT }}
-      #     password: ${{ secrets.QUAY_ROBOT_TOKEN }}
-      #
-      # - name: "Push Images to Quay"
-      #   if: ${{ !inputs.dry_run }}
-      #   run: |
-      #     # TODO: remove this
-      #     exit 1
-      #     for image in ${{ vars.PUBLISH_IMAGES_LIST }}; do
-      #       echo "Pushing $image to Quay"
-      #
-      #       if [ "${{ env.OSL_IMAGE_TAG }}" = "main" ]; then
-      #         echo "OSL_IMAGE_TAG is 'main'. Pushing main tag."
-      #         docker push quay.io/kubesmarts/$image:main || { echo "Failed to push $image:main"; exit 1; }
-      #       else
-      #         echo "OSL_IMAGE_TAG is not 'main'. Tagging and pushing snapshot."
-      #         docker tag quay.io/kubesmarts/$image:main quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }}
-      #         docker push quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push $image with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
-      #       fi
-      #     done
+      - name: "Build Images"
+        env:
+          DROOLS_AND_KOGITO__skip: true
+          KOGITO_RUNTIME_version: "${{ inputs.KOGITO_VERSION }}"
+          KIE_TOOLS_BUILD__buildContainerImages: "true"
+          KIE_TOOLS_BUILD__runEndToEndTests: "false"
+          KIE_TOOLS_BUILD__runTests:
+            "false"
+            # TODO: on upstream implement a root-env named defaultRegistry and defaultAccount and change on every image package
+          SONATAFLOW_BUILDER_IMAGE__registry: "quay.io"
+          SONATAFLOW_BUILDER_IMAGE__account: "kubesmarts"
+          SONATAFLOW_DEVMODE_IMAGE__registry: "quay.io"
+          SONATAFLOW_DEVMODE_IMAGE__account: "kubesmarts"
+          SONATAFLOW_MANAGEMENT_CONSOLE__registry: "quay.io"
+          SONATAFLOW_MANAGEMENT_CONSOLE__account: "kubesmarts"
+          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__registry: "quay.io"
+          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__account: "kubesmarts"
+          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__registry: "quay.io"
+          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__account: "kubesmarts"
+          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__registry: "quay.io"
+          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__account: "kubesmarts"
+          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__registry: "quay.io"
+          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__account: "kubesmarts"
+          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageRegistry: "quay.io"
+          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageAccount: "kubesmarts"
+          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageRegistry: "quay.io"
+          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageAccount: "kubesmarts"
+          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageRegistry: "quay.io"
+          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageAccount: "kubesmarts"
+          # SONATAFLOW_QUARKUS_DEVUI_VERSION: "${{ inputs.KOGITO_VERSION }}"
+          # SONATAFLOW_DEVMODE_IMAGE__sonataflowQuarkusDevUiVersion: "${{ inputs.KOGITO_VERSION }}"
+          DASHBUILDER__viewerImageRegistry: "quay.io"
+          DASHBUILDER__viewerImageAccount: "kubesmarts"
+          SONATAFLOW_OPERATOR__registry: "quay.io"
+          SONATAFLOW_OPERATOR__account: "kubesmarts"
+          KOGITO_DB_MIGRATOR_TOOL_IMAGE__registry: "quay.io"
+          KOGITO_DB_MIGRATOR_TOOL_IMAGE__account: "kubesmarts"
+        shell: bash
+        run: |
+          eval "pnpm ${{ vars.IMAGES_UPSTREAM_PNPM_FILTER }} --workspace-concurrency=1 build:prod"
+
+      - name: "Login to Quay"
+        uses: docker/login-action@v3
+        with:
+          registry: quay.io
+          username: ${{ secrets.QUAY_ROBOT_ACCOUNT }}
+          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
+
+      - name: "Push Images to Quay"
+        if: ${{ !inputs.dry_run }}
+        run: |
+          # TODO: remove this
+          exit 1
+          for image in ${{ vars.PUBLISH_IMAGES_LIST }}; do
+            echo "Pushing $image to Quay"
+
+            if [ "${{ env.OSL_IMAGE_TAG }}" = "main" ]; then
+              echo "OSL_IMAGE_TAG is 'main'. Pushing main tag."
+              docker push quay.io/kubesmarts/$image:main || { echo "Failed to push $image:main"; exit 1; }
+            else
+              echo "OSL_IMAGE_TAG is not 'main'. Tagging and pushing snapshot."
+              docker tag quay.io/kubesmarts/$image:main quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }}
+              docker push quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push $image with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
+            fi
+          done
