Build and publish operator bundle and catalog.

diff --git a/.github/workflows/osl_publish_images_snapshots.yml b/.github/workflows/osl_publish_images_snapshots.yml
--- a/.github/workflows/osl_publish_images_snapshots.yml
+++ b/.github/workflows/osl_publish_images_snapshots.yml
@@ -20,6 +20,16 @@ on:
         type: string
         required: false
         default: "main"
+      build_operator_bundle:
+        description: "Flag to build operator bundle."
+        type: boolean
+        required: false
+        default: true
+      build_operator_catalog:
+        description: "Flag to build operator catalog."
+        type: boolean
+        required: false
+        default: true
 
 permissions:
   contents: read
@@ -27,7 +37,40 @@ permissions:
 jobs:
   publish_images_snapshots:
     runs-on: ubuntu-latest
-
+    env:
+      DROOLS_AND_KOGITO__skip: true
+      KOGITO_RUNTIME_version: "${{ inputs.KOGITO_VERSION }}"
+      SONATAFLOW_DEVMODE_IMAGE__sonataflowQuarkusDevUiVersion: "${{ inputs.KOGITO_VERSION }}"
+      KIE_TOOLS_BUILD__buildContainerImages: "true"
+      KIE_TOOLS_BUILD__runEndToEndTests: "false"
+      KIE_TOOLS_BUILD__runTests: "false"
+      # TODO: on upstream implement a root-env named defaultRegistry and defaultAccount and change on every image package
+      SONATAFLOW_BUILDER_IMAGE__registry: "quay.io"
+      SONATAFLOW_BUILDER_IMAGE__account: "kubesmarts"
+      SONATAFLOW_DEVMODE_IMAGE__registry: "quay.io"
+      SONATAFLOW_DEVMODE_IMAGE__account: "kubesmarts"
+      SONATAFLOW_MANAGEMENT_CONSOLE__registry: "quay.io"
+      SONATAFLOW_MANAGEMENT_CONSOLE__account: "kubesmarts"
+      KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__registry: "quay.io"
+      KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__account: "kubesmarts"
+      KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__registry: "quay.io"
+      KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__account: "kubesmarts"
+      KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__registry: "quay.io"
+      KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__account: "kubesmarts"
+      KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__registry: "quay.io"
+      KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__account: "kubesmarts"
+      SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageRegistry: "quay.io"
+      SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageAccount: "kubesmarts"
+      SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageRegistry: "quay.io"
+      SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageAccount: "kubesmarts"
+      SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageRegistry: "quay.io"
+      SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageAccount: "kubesmarts"
+      DASHBUILDER__viewerImageRegistry: "quay.io"
+      DASHBUILDER__viewerImageAccount: "kubesmarts"
+      SONATAFLOW_OPERATOR__registry: "quay.io"
+      SONATAFLOW_OPERATOR__account: "kubesmarts"
+      KOGITO_DB_MIGRATOR_TOOL_IMAGE__registry: "quay.io"
+      KOGITO_DB_MIGRATOR_TOOL_IMAGE__account: "kubesmarts"
     steps:
       - name: "Print workflow inputs"
         run: |
@@ -76,44 +119,19 @@ jobs:
           USE_REMOTE_ARTIFACTS: ${{ inputs.USE_REMOTE_ARTIFACTS }}
 
       - name: "Build Images"
-        env:
-          DROOLS_AND_KOGITO__skip: true
-          KOGITO_RUNTIME_version: "${{ inputs.KOGITO_VERSION }}"
-          SONATAFLOW_DEVMODE_IMAGE__sonataflowQuarkusDevUiVersion: "${{ inputs.KOGITO_VERSION }}"
-          KIE_TOOLS_BUILD__buildContainerImages: "true"
-          KIE_TOOLS_BUILD__runEndToEndTests: "false"
-          KIE_TOOLS_BUILD__runTests:
-            "false"
-            # TODO: on upstream implement a root-env named defaultRegistry and defaultAccount and change on every image package
-          SONATAFLOW_BUILDER_IMAGE__registry: "quay.io"
-          SONATAFLOW_BUILDER_IMAGE__account: "kubesmarts"
-          SONATAFLOW_DEVMODE_IMAGE__registry: "quay.io"
-          SONATAFLOW_DEVMODE_IMAGE__account: "kubesmarts"
-          SONATAFLOW_MANAGEMENT_CONSOLE__registry: "quay.io"
-          SONATAFLOW_MANAGEMENT_CONSOLE__account: "kubesmarts"
-          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__registry: "quay.io"
-          KOGITO_DATA_INDEX_EPHEMERAL_IMAGE__account: "kubesmarts"
-          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__registry: "quay.io"
-          KOGITO_DATA_INDEX_POSTGRESQL_IMAGE__account: "kubesmarts"
-          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__registry: "quay.io"
-          KOGITO_JOBS_SERVICE_EPHEMERAL_IMAGE__account: "kubesmarts"
-          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__registry: "quay.io"
-          KOGITO_JOBS_SERVICE_POSTGRESQL_IMAGE__account: "kubesmarts"
-          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageRegistry: "quay.io"
-          SERVERLESS_LOGIC_WEB_TOOLS__swfBuilderImageAccount: "kubesmarts"
-          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageRegistry: "quay.io"
-          SERVERLESS_LOGIC_WEB_TOOLS__baseBuilderImageAccount: "kubesmarts"
-          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageRegistry: "quay.io"
-          SERVERLESS_LOGIC_WEB_TOOLS__swfDevModeImageAccount: "kubesmarts"
-          DASHBUILDER__viewerImageRegistry: "quay.io"
-          DASHBUILDER__viewerImageAccount: "kubesmarts"
-          SONATAFLOW_OPERATOR__registry: "quay.io"
-          SONATAFLOW_OPERATOR__account: "kubesmarts"
-          KOGITO_DB_MIGRATOR_TOOL_IMAGE__registry: "quay.io"
-          KOGITO_DB_MIGRATOR_TOOL_IMAGE__account: "kubesmarts"
         shell: bash
         run: |
           eval "pnpm ${{ vars.IMAGES_UPSTREAM_PNPM_FILTER }} --workspace-concurrency=1 build:prod"
+
+      - name: "Build operator bundle"
+        if: ${{ inputs.build_operator_bundle }}
+        run: |
+          eval "pnpm @kie-tools/sonataflow-operator --workspace-concurrency=1 image:bundle:build"
+
+      - name: "Build operator catalog"
+        if: ${{ inputs.build_operator_catalog }}
+        run: |
+          eval "pnpm @kie-tools/sonataflow-operator --workspace-concurrency=1 image:catalog:build"
 
       - name: "Login to Quay"
         uses: docker/login-action@v3
@@ -137,3 +155,31 @@ jobs:
               docker push quay.io/kubesmarts/$image:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push $image with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
             fi
           done
+
+      - name: "Push operator bundle to Quay"
+        if: ${{ !inputs.dry_run }}
+        run: |
+          echo "Pushing operator bundle to Quay"
+
+          if [ "${{ env.OSL_IMAGE_TAG }}" = "main" ]; then
+            echo "OSL_IMAGE_TAG is 'main'. Pushing main tag."
+            docker push quay.io/kubesmarts/incubator-kie-sonataflow-operator-bundle:main || { echo "Failed to push incubator-kie-sonataflow-operator-bundle:main"; exit 1; }
+          else
+            echo "OSL_IMAGE_TAG is not 'main'. Tagging and pushing snapshot."
+            docker tag quay.io/kubesmarts/incubator-kie-sonataflow-operator-bundle:main quay.io/kubesmarts/incubator-kie-sonataflow-operator-bundle:${{ env.OSL_IMAGE_TAG }}
+            docker push quay.io/kubesmarts/incubator-kie-sonataflow-operator-bundle:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push incubator-kie-sonataflow-operator-bundle with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
+          fi
+
+      - name: "Push operator catalog to Quay"
+        if: ${{ !inputs.dry_run }}
+        run: |
+          echo "Pushing operator catalog to Quay"
+
+          if [ "${{ env.OSL_IMAGE_TAG }}" = "main" ]; then
+            echo "OSL_IMAGE_TAG is 'main'. Pushing main tag."
+            docker push quay.io/kubesmarts/incubator-kie-sonataflow-operator-catalog:main || { echo "Failed to push incubator-kie-sonataflow-operator-catalog:main"; exit 1; }
+          else
+            echo "OSL_IMAGE_TAG is not 'main'. Tagging and pushing snapshot."
+            docker tag quay.io/kubesmarts/incubator-kie-sonataflow-operator-catalog:main quay.io/kubesmarts/incubator-kie-sonataflow-operator-bundle:${{ env.OSL_IMAGE_TAG }}
+            docker push quay.io/kubesmarts/incubator-kie-sonataflow-operator-catalog:${{ env.OSL_IMAGE_TAG }} || { echo "Failed to push incubator-kie-sonataflow-operator-catalog with tag $OSL_IMAGE_TAG to Quay"; exit 1; }
+          fi
